package com.example.student_attendens_app_recycleview
object DataManager {
    val students = mutableListOf<Student>()

    init {
        createMockData()
    }

    //
    fun createMockData() {
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
        students.add(Student("Eva", "AU20"))
        students.add(Student("Elin", "AU22", true))
        students.add(Student("Emma", "AU22", true))
        students.add(Student("Noah", "AU22"))
        students.add(Student("Leah", "AU22"))
        students.add(Student("Johan", "AU22"))
        students.add(Student("Martina", "AU22"))
    }
}